openapi: 3.0.0

info:
  title: "Title"
  description: "Description"
  version: 0.0.1

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        dob:
          type: date
        race:
          $ref: '#/components/schemas/Race'
        contact_info:
          type: object
          properties:
            email:
              type: string
              format: email
            phone:
              type: string
          required:
            - phone
        favoriteMovies:
          type: array
          items:
            $ref: '#/components/schemas/Movie'
      required:
        - id
        - name
        - dob

    Race:
      type: string
      enum:
        - black
        - white
        - hispanic
        - asian

    Movie:
      type: object
      properties:
        title:
          type: string
      required:
        - title


paths: {}