openapi: 3.0.0

info:
  title: "Title"
  description: "Description"
  version: 0.0.1

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        dob:
          type: date
        contact_info:
          type: object
          properties:
            email:
              type: string
              format: email
            phone:
              type: string
          required:
            - phone
      required:
        - id
        - name
        - dob